on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Build and deploy to Docker Hub

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: c4stus/speedcube-events
        tags: type=sha

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        platforms: |
          linux/amd64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to charts repo
      run: |
        set -e
        image_version=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ":" -f 2)
        curl -w "%{response_code}" -X POST https://api.github.com/repos/castus/speedcube-events-charts/dispatches \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.CHARTS_DEPLOY_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        --data '{"event_type": "deploy", "client_payload": { "image_tag": "'"$image_version"'" }}'
